dbp_relay_auth:
  server_url: '%env(AUTH_SERVER_URL)%'
  # OpenAPI Docs Keycloak Settings
  frontend_keycloak_server: '%env(AUTH_APIDOCS_KEYCLOAK_SERVER)%'
  frontend_keycloak_realm: '%env(AUTH_APIDOCS_KEYCLOAK_REALM)%'
  frontend_keycloak_client_id: '%env(AUTH_APIDOCS_KEYCLOAK_CLIENT_ID)%'