services:
  App\Service\:
    resource: '../src/Service'
    autowire: true

  # Replace the core one with our custom (dummy) implementation.
  DBP\API\CoreBundle\Service\PersonProviderInterface: '@App\Service\MyCustomPersonProvider'